# SPDX-FileCopyrightText: Copyright Â© 2024 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

version = 1
[[annotations]]
path = "**/*.lockfile"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
[[annotations]]
path = "**/package-lock.json"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
