# SPDX-FileCopyrightText: Copyright Â© 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: precommit
on: [push, workflow_call]
jobs:
  license:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_branch}}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: "3"
      - run: pip install -r requirements.txt
      - run: reuse lint
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_branch}}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-node@v5.0.0
        with:
          cache: "npm"
      - run: npm ci
      - run: npx prettier --ignore-unknown --check '**'
  format-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_branch}}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - uses: asdf-vm/actions/plugins-add@v4.0.0
      - run: asdf install ktlint
      - run: ktlint '*.gradle.kts' '**/*.gradle.kts'
