# SPDX-FileCopyrightText: Copyright Â© 2024 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: update-node
on:
  schedule:
    - cron: "0 4 * * 0"
  push:
    branches:
      - ci/auto-update-node
      - ci/auto-update
jobs:
  update-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch}}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm install
      - run: npm update
      - uses: peter-evans/create-pull-request@v7
        id: create_pr
        with:
          title: "chore(deps): update node"
          branch: topic/update-node
          token: ${{ secrets.GH_MERGE_PAT }}
      - run: gh pr merge --auto --squash ${{ steps.create_pr.outputs.pull-request-number }}
        if: ${{ steps.create_pr.outputs.pull-request-number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_MERGE_PAT }}
